In [19]:
import numpy as np
from simplex_implementation import simplex
np.set_printoptions(edgeitems=30, linewidth=100000, suppress=True, precision=3)

In [20]:
## Basic Example
'''
Problem inputed is:

maximize    5x + 5y + 3z
subject to  x + 3y + z <= 3
            -x + 3z <= 2
            2x - y + 2z <= 4
            2x + 3y - z <= 2

The solution should be (1.103, 0.276, 1.034)
'''
c = np.array([5, 5, 3])
A_l = np.array([[1, 3, 1], [-1, 0, 3], [2, -1, 2], [2, 3, -1]])
b_l = np.array([3, 2, 4, 2])

simplex(c, A_lt = A_l, b_lt = b_l)

array([1.103, 0.276, 1.034])

In [21]:
## Another Basic Example
'''
Problem inputed is:

maximize    15x + 25y
subject to  x + y <= 450
            y <= 300
            4x + 5y <= 2000
            x <= 350

The solution should be (125, 300)
'''
c = np.array([15, 25])
A_l = np.array([[1, 1], [0, 1], [4, 5], [1, 0]])
b_l = np.array([450, 300, 2000, 350])

simplex(c, A_lt = A_l, b_lt = b_l)

array([125., 300.])

In [22]:
## Another Basic Example
'''
Problem inputed is:

maximize    5x + 4y + 3z
subject to  2x + 3y + z <= 5
            4x + y + 2z <= 11
            3x + 4y + 2z <= 8

The solution should be (2, 0, 1)
'''
c = np.array([5, 4, 3])
A_l = np.array([[2, 3, 1], [4, 1, 2], [3, 4, 2]])
b_l = np.array([5, 11, 8])

simplex(c, A_lt = A_l, b_lt = b_l)

array([2., 0., 1.])

In [23]:
## Unboundedness Example
'''
Problem inputed is:

maximize    -25x + 4y
subject to  14x - y <= 25
            x <= 30
            -5x - 14y <= 12
            4x - 7y <= 22

The solution should be (0, inf)
'''
c = np.array([-25, 4])
A_l = np.array([[14, -1], [1, 0], [-5, -14], [4, -7]])
b_l = np.array([25, 30, 12, 22])

simplex(c, A_lt = A_l, b_lt = b_l)

array([ 0., inf])

In [24]:
## Cycling Example
'''
Problem inputed is:

maximize    5w + 4x - 20y - 2z
subject to  1/4w - 1/8x + 12y + 10z <= 0
            1/10w + 1/20x + 1/20y + 1/5z <= 0

The solution should be (0, 0, 0, 0)
'''
c = np.array([5, 4, -20, -2])
A_l = np.array([[1/4, -1/8, 12, 10], [1/10, 1/20, 1/20, 1/5]])
b_l = np.array([0, 0])

simplex(c, A_lt = A_l, b_lt = b_l)

array([0., 0., 0., 0.])

In [25]:
## Degenerate Initialization Example
'''
Problem inputed is:

maximize    15x + 25y
subject to  x + y <= 450
            y <= 300
            4x + 5y <= 2000
            x <= 350
            x + y >= 100

The solution should be (125, 300)
'''
c = np.array([15, 25])
A_l = np.array([[1, 1], [0, 1], [4, 5], [1, 0], [-1, -1]])
b_l = np.array([450, 300, 2000, 350, -100])

simplex(c, A_lt = A_l, b_lt = b_l)

array([125., 300.])

In [26]:
## Another Degenerate Initialization Example
'''
Problem inputed is:

maximize    x - 2y + 3z
subject to  -2x + 3y + 4z >= 12
            3x + 2y + z >= 6
            x + y + z <= 9

The solution should be (0, 0, 9)
'''
c = np.array([1, -2, 3])
A_l = np.array([[2, -3, -4], [-3, -2, -1], [1, 1, 1]])
b_l = np.array([-12, -6, 9])

simplex(c, A_lt = A_l, b_lt = b_l)

array([0., 0., 9.])

In [27]:
## Another Degenerate Initialization Example
'''
Problem inputed is:

maximize    x + y
subject to  2x + y <= 29
            2x + 4y <= 50
            x >= 5
            y >= 2

The solution should be (11, 7)
'''
c = np.array([1, 1])
A_l = np.array([[2, 1], [2, 4], [-1, 0], [0, -1]])
b_l = np.array([29, 50, -5, -2])

simplex(c, A_lt = A_l, b_lt = b_l)

array([11.,  7.])

In [28]:
## No feasible region example
'''
Problem inputed is:

maximize    x + y
subject to  x + y <= 11
            x >= 6
            y >= 6

The solution should be (NaN, NaN)
'''
c = np.array([1, 1])
A_l = np.array([[1, 1], [-1, 0], [0, -1]])
b_l = np.array([11, -6, -6])

simplex(c, A_lt = A_l, b_lt = b_l)

array([nan, nan])

In [29]:
## Rewrite Equality
'''
Problem inputed is:

maximize    15x + 25y
subject to  x + y <= 450
            y <= 300
            4x + 5y <= 2000
            x <= 350

The solution should be (125, 300)
'''
c = np.array([15, 25])
A_l = np.array([[1, 1], [0, 1], [4, 5], [1, 0]])
b_l = np.array([450, 300, 2000, 350])
A_g = np.array([[0, 1], [1, 1]])
b_g = np.array([300, 100])

simplex(c, A_lt=A_l, b_lt=b_l, A_gt=A_g, b_gt=b_g)

array([125., 300.])